---
- name: Remove and clean in remote host
  hosts: all
  remote_user: ychibani
  become: true
  tasks:
    - name: Run make fclean
      become_user: ychibani
      command: make fclean
      args:
        chdir: /home/ychibani/cloud-1
    - name: Remove cloud-1 directory
      become: true
      file:
        path: /home/ychibani/cloud-1
        state: absent
    - name: Remove data directory
      become: true
      file:
        path: /home/ychibani/cloud-1/data
        state: absent