- name: Setup Instance
  hosts: all
  remote_user: "{{ ansible_user }}"
  become: true
  tasks:
    - name: Ensure make is installed
      apt:
        name: make
        state: present
      register: result
      until: result is succeeded
      retries: 3
      delay: 10

    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - gnupg
          - python3
          - pip
        state: latest
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install docker-compose from official GitHub repo
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Create or modify /etc/docker/daemon.json to use cgroupfs
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "exec-opts": ["native.cgroupdriver=cgroupfs"]
          }
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart docker

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add the user to Docker group
      command: usermod -aG docker "{{ ansible_user }}"

    - name: Restart the Docker service to ensure permissions
      service:
        name: docker
        state: restarted

    - name: Set Domain Name to static IP 
      shell: |
        export DOMAIN_NAME={{ ansible_host }}
    
  handlers:
    - name: restart docker
      systemd:
        name: docker
        state: restarted
        enabled: yes